"use client";

import React from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Minus, Plus, Search, X } from "lucide-react";

export const faqs = [
  // 1. General Overview
  {
    q: "What is NextNews?",
    a: "NextNews is an AI-powered news aggregator that brings together curated categories, top headlines, and live coverage, allowing you to follow what matters most without losing context.",
  },
  {
    q: "How is NextNews different from other news apps?",
    a: "Unlike traditional news apps, NextNews uses advanced AI to distill complex articles into bite-sized summaries, groups related stories to avoid bias, and deeply personalizes your feed over time.",
  },
  {
    q: "Is there a mobile app available?",
    a: "Yes, our mobile app is available for iOS and Android, allowing you to read seamlessly on the go with real-time notifications.",
  },
  {
    q: "What languages does NextNews support?",
    a: "Currently, NextNews fully supports English, Spanish, French, German, and Japanese, with more languages rolling out soon.",
  },
  {
    q: "How often is the news updated?",
    a: "Our platform aggregates data 24/7, providing real-time updates and breaking news alerts almost instantly.",
  },
  {
    q: "Who curates the news on NextNews?",
    a: "We aggregate news from thousands of verified global publishers. Our AI then categorizes and summarizes the content, while keeping the original context intact.",
  },
  {
    q: "Can I use NextNews on my tablet or iPad?",
    a: "Yes, our web application and mobile apps are fully responsive and optimized for a seamless tablet reading experience.",
  },
  {
    q: "Do I need an internet connection to use the app?",
    a: "You need an internet connection to receive live updates, but premium users can download articles and entire categories for offline reading.",
  },
  {
    q: "Are the AI summaries generated by humans?",
    a: "No, our summaries are automatically generated using advanced large language models trained specifically for journalistic integrity and neutrality.",
  },
  {
    q: "How do I report a bug or issue?",
    a: "You can report any bugs or issues directly through the 'Support' section in your account dashboard, or email us at support@nextnews.co.in.",
  },

  // 2. Getting Started
  {
    q: "How do I create an account?",
    a: "Click on 'Explore' or 'My Activity' when logged out to navigate to the registration page. You can sign up using your email or social accounts.",
  },
  {
    q: "Do I need to pay to use NextNews?",
    a: "NextNews offers a generous free tier with access to breaking news and basic personalization. Premium features require a paid subscription.",
  },
  {
    q: "How do I select my favorite topics?",
    a: "During onboarding, you'll be prompted to select categories. You can always update these later in the 'My Activity' or settings page.",
  },
  {
    q: "Can I skip the onboarding process?",
    a: "Yes, you can skip onboarding and jump straight into the top global headlines, adjusting your preferences later.",
  },
  {
    q: "What happens if I forget my password?",
    a: "Click 'Forgot Password' on the login screen. We will send a secure reset link to your registered email address.",
  },
  {
    q: "How do I change my region preferences?",
    a: "Navigate to your profile settings, locate the 'Region & Language' tab, and update your primary location to receive localized news.",
  },
  {
    q: "Can I follow specific journalists or authors?",
    a: "Currently, you can follow specific topics and publishers. Author-specific following is a planned feature for an upcoming update.",
  },
  {
    q: "How do I turn on dark mode?",
    a: "NextNews automatically syncs with your device's system theme. You can also manually toggle dark mode in the profile settings.",
  },
  {
    q: "Where can I find the breaking news section?",
    a: "Breaking news is pinned to the top of your personalized Explore feed and highlighted with a red 'Live' indicator.",
  },
  {
    q: "How do I sign out of my account?",
    a: "Click on your avatar in the top right corner and select 'Log Out' from the dropdown menu.",
  },

  // 3. AI & Personalization
  {
    q: "How does the AI personalize my feed?",
    a: "Our AI analyzes the categories you click, the articles you read fully, and the topics you save, continuously refining your feed to show highly relevant stories.",
  },
  {
    q: "How accurate are the AI summaries?",
    a: "Our AI summaries are rigorously tested against the source material to ensure factual accuracy and neutrality. We constantly update our models to prevent hallucinations.",
  },
  {
    q: "Will the AI trap me in an echo chamber?",
    a: "No. A core feature of NextNews is 'Balanced Perspectives,' where the AI actively groups related stories from differing viewpoints so you get the full picture.",
  },
  {
    q: "Can I turn off AI summaries?",
    a: "Yes, if you prefer to only read full articles from original publishers, you can disable AI summaries in your reading preferences.",
  },
  {
    q: "How long does it take for the AI to learn my preferences?",
    a: "You will start noticing a tailored feed within your first 5-10 article interactions.",
  },
  {
    q: "Can I manually train the AI?",
    a: "Yes! Using the 'Show more like this' or 'Show less like this' buttons on articles gives the AI direct instructions.",
  },
  {
    q: "Does the AI translate foreign news articles?",
    a: "Yes, premium users can enable automatic translation for over 40 languages, bringing global news to your native language.",
  },
  {
    q: "What is the 'Deep Context' feature?",
    a: "Deep Context is an AI tool that scans articles and provides bullet points on historical background and related events to help you understand complex ongoing stories.",
  },
  {
    q: "Are opinion pieces labeled by the AI?",
    a: "Yes, our AI actively distinguishes between factual reporting and opinion/editorial pieces, tagging them clearly in your feed.",
  },
  {
    q: "How does the AI handle clickbait?",
    a: "Our AI evaluates headlines against article content. If a headline is deemed misleading, the AI generates a more accurate, neutral headline for your feed.",
  },

  // 4. Premium Features & Subscriptions
  {
    q: "What is included in the Premium subscription?",
    a: "Premium unlocks unlimited AI summaries, offline reading, ad-free browsing, advanced personalization, and Deep Context background generation.",
  },
  {
    q: "What are AI credits and how do they work?",
    a: "AI credits are weighted points for using AI features like summaries and suggestions. Summaries cost 1 credit, personalized suggestions cost 2 credits, and region suggestions cost 2 credits.",
  },
  {
    q: "What's the free plan credit limit?",
    a: "Free users get a 16-day trial with 20 weighted AI credits. After using 20 credits or 16 days pass, you'll need to upgrade to a paid plan.",
  },
  {
    q: "What happens after my free 16 days end?",
    a: "Your free access expires after 16 days. You can then choose a paid plan (Pro or Pro+) to continue using AI features and access premium content.",
  },
  {
    q: "What is the 12-day cooldown after free credits run out?",
    a: "After using all 20 free AI credits, you enter a 12-day waiting period before you can use AI features again (unless you upgrade to a paid plan for immediate access).",
  },
  {
    q: "Can I use remaining credits after canceling my paid plan?",
    a: "Yes! If you cancel a paid plan, you can continue using any remaining credits until they're fully consumed or your plan access expires.",
  },
  {
    q: "How much does NextNews Premium cost?",
    a: "Please visit our Pricing page for the most up-to-date information on monthly and annual subscription plans.",
  },
  {
    q: "Can I cancel my subscription at any time?",
    a: "Absolutely. You can cancel your subscription from your account billing settings. Your premium features will remain active until the end of your billing cycle.",
  },
  {
    q: "Do you offer a free trial for Premium?",
    a: "Yes, new users are eligible for a 16-day free trial of NextNews Premium upon registration.",
  },
  {
    q: "What payment methods do you accept?",
    a: "We accept all major credit cards, PayPal, Apple Pay, and Google Pay.",
  },
  {
    q: "Is there a discount for students or educators?",
    a: "Yes! We offer a 50% discount for verified students and educators. Contact support with your .edu email to apply.",
  },
  {
    q: "Can I share my Premium account with my family?",
    a: "Currently, Premium accounts are for individual use. We plan to introduce family plans in the near future.",
  },
  {
    q: "Will I see ads if I am a Premium member?",
    a: "No, NextNews Premium provides a completely ad-free reading experience.",
  },
  {
    q: "How do I upgrade my free account to Premium?",
    a: "Navigate to the 'Pricing' or 'Plans' page from the main navigation menu and select the plan that fits your needs.",
  },
  {
    q: "Can I get a refund if I forget to cancel my trial?",
    a: "We offer a 7-day grace period for refunds after a trial converts to a paid subscription. Please contact support immediately.",
  },

  // 5. Account Management
  {
    q: "How do I change my email address?",
    a: "Go to your Account Settings, select 'Security,' and enter your new email address. You will need to verify the new email via a confirmation link.",
  },
  {
    q: "How do I delete my account?",
    a: "You can permanently delete your account and all associated data from the bottom of your Account Settings page.",
  },
  {
    q: "Can I link multiple devices to one account?",
    a: "Yes, you can log in on up to 5 devices simultaneously.",
  },
  {
    q: "What should I do if I suspect my account is compromised?",
    a: "Change your password immediately and log out of all active sessions from your security settings. Then, contact our support team.",
  },
  {
    q: "How do I update my profile picture?",
    a: "Click on your avatar, select 'Edit Profile,' and upload a new image from your device.",
  },
  {
    q: "Why am I not receiving email newsletters?",
    a: "Check your spam folder first. If they aren't there, ensure your email preferences in the settings menu have 'Newsletters' enabled.",
  },
  {
    q: "Can I change my username?",
    a: "Yes, your display username can be changed once every 30 days in your profile settings.",
  },
  {
    q: "How do I view my billing history?",
    a: "Navigate to Account Settings > Billing. You can view and download all past invoices there.",
  },
  {
    q: "Is two-factor authentication (2FA) available?",
    a: "Yes, we highly recommend enabling 2FA in your security settings to protect your account.",
  },
  {
    q: "How do I switch from an annual to a monthly plan?",
    a: "You can change your billing frequency in the Billing section. The change will take effect at the end of your current billing cycle.",
  },

  // 6. Offline & Saved Content
  {
    q: "How do I save an article for later?",
    a: "Click the bookmark icon located on any article card or at the top of the article page.",
  },
  {
    q: "Where do I find my saved articles?",
    a: "All saved articles are located in the 'My Activity' dashboard under the 'Saved' tab.",
  },
  {
    q: "How do I download articles for offline reading?",
    a: "Premium users can click the 'Download' icon on any article or category to save the text locally to their device.",
  },
  {
    q: "Is there a limit to how many articles I can save?",
    a: "Free users can save up to 100 articles. Premium users have unlimited saves.",
  },
  {
    q: "Do downloaded articles expire?",
    a: "Downloaded articles remain on your device until you manually delete them or clear your app cache.",
  },
  {
    q: "Can I organize my saved articles into folders?",
    a: "Yes, Premium users can create custom collections to organize saved stories.",
  },
  {
    q: "Are images saved for offline reading?",
    a: "By default, only text is saved to conserve space. You can enable 'Download High-Res Images' in settings.",
  },
  {
    q: "How do I delete a saved article?",
    a: "Click the bookmark icon again to unsave an article, or manage them in bulk from the 'My Activity' page.",
  },
  {
    q: "Can I highlight text in articles?",
    a: "Yes, simply select the text and tap 'Highlight.' Your highlights will be saved to your notes dashboard.",
  },
  {
    q: "Can I share my collections with friends?",
    a: "Yes, you can generate a public link for any custom collection to share your curated reading list.",
  },

  // 7. Privacy & Security
  {
    q: "How does NextNews use my reading data?",
    a: "We use your reading data strictly to train your personal AI algorithm and improve your feed. We never sell your data to third parties.",
  },
  {
    q: "Is my personal information secure?",
    a: "Yes, we use industry-standard end-to-end encryption to protect your account credentials and personal data.",
  },
  {
    q: "Can I opt out of data tracking?",
    a: "Yes, you can enable 'Incognito Reading' mode to prevent articles from affecting your personalized feed.",
  },
  {
    q: "What is your privacy policy?",
    a: "You can read our comprehensive privacy policy by clicking the 'Privacy Policy' link in the website footer.",
  },
  {
    q: "Do you share my email with advertisers?",
    a: "Absolutely not. NextNews maintains a strict no-sale policy regarding user contact information.",
  },
  {
    q: "How do I request a copy of my data?",
    a: "You can download an archive of all your account data, reading history, and saved articles from your privacy settings.",
  },
  {
    q: "Are the payment processors secure?",
    a: "Yes, we use Dodo Payments, a secure and compliant payment gateway, to handle all transactions securely.",
  },
  {
    q: "Does NextNews track my location?",
    a: "We use approximate IP-based location to provide relevant regional news. You can manually set a region and disable location tracking entirely.",
  },
  {
    q: "What happens to my data if I delete my account?",
    a: "All personal data, reading history, and preferences are permanently purged from our servers within 30 days of account deletion.",
  },
  {
    q: "Are there third-party trackers on the site?",
    a: "We use minimal analytics to monitor site performance. Premium members experience zero third-party ad tracking.",
  },

  // 8. Troubleshooting & Technical Support
  {
    q: "Why is my feed not updating?",
    a: "Try refreshing the page or pulling down to refresh on mobile. If the issue persists, check your internet connection or clear your browser cache.",
  },
  {
    q: "The AI summary generated an error. What do I do?",
    a: "Occasionally, complex paywalls prevent our AI from summarizing. Please click the 'Report Issue' flag next to the summary.",
  },
  {
    q: "Why can't I log in?",
    a: "Ensure you are using the correct email and password. If you use a social login, make sure you select the provider you originally registered with.",
  },
  {
    q: "The app keeps crashing on my Android device.",
    a: "Please ensure you have updated the app to the latest version via the Google Play Store. Clearing the app data may also help.",
  },
  {
    q: "I paid for Premium but my features are locked.",
    a: "Try logging out and logging back in to refresh your token. If that doesn't work, contact support with your invoice number.",
  },
  {
    q: "Why are images not loading?",
    a: "If you have a slow connection, NextNews prioritizes text. Check if you have 'Data Saver Mode' enabled in your settings.",
  },
  {
    q: "How do I stop browser notifications?",
    a: "You can disable push notifications via your browser's site settings or from the 'Notifications' tab in your NextNews account.",
  },
  {
    q: "The website layout looks broken.",
    a: "Please disable any aggressive ad-blockers or script-blockers that might be interfering with our site's CSS and Javascript.",
  },
  {
    q: "I'm receiving too many emails.",
    a: "You can manage your email frequency or unsubscribe from specific newsletters in your Account Settings > Notifications.",
  },
  {
    q: "How do I contact a live support agent?",
    a: "Premium members have access to live chat support. Free users can submit a ticket via email which typically receives a response within 24 hours.",
  },

  // 9. Extra & Miscellaneous
  {
    q: "Can I become a contributor for NextNews?",
    a: "We occasionally partner with freelance journalists and curators. Check the 'Work With Us' section in the footer for opportunities.",
  },
  {
    q: "Do you have an API available for developers?",
    a: "Yes, we offer an enterprise API for accessing our curated news and AI summaries. Contact our sales team for documentation.",
  },
  {
    q: "How do I submit an article for inclusion?",
    a: "We rely on trusted publisher feeds. If you represent a publication, you can submit your RSS feed for review via our contact page.",
  },
  {
    q: "Where is NextNews headquartered?",
    a: "NextNews is a remote-first company with our primary hub located in India.",
  },
  {
    q: "Is there a community forum?",
    a: "We are currently beta-testing a community feature where readers can discuss stories. Stay tuned for announcements!",
  },
];

const desktopVariants = {
  initial: { opacity: 0, y: 20, scale: 0.95 },
  animate: { opacity: 1, y: 0, scale: 1 },
  exit: { opacity: 0, y: 20, scale: 0.95 },
};

const mobileVariants = {
  initial: { opacity: 0, y: "100%" },
  animate: { opacity: 1, y: 0 },
  exit: { opacity: 0, y: "100%" },
};

export function FAQSection() {
  const [openFaqIndex, setOpenFaqIndex] = React.useState<number | null>(null);
  const [searchQuery, setSearchQuery] = React.useState("");
  const [isAllQuestionsOpen, setIsAllQuestionsOpen] = React.useState(false);
  const [popupOpenFaqIndex, setPopupOpenFaqIndex] = React.useState<
    number | null
  >(null);
  const [isMobile, setIsMobile] = React.useState(false);
  const [shuffledFaqs, setShuffledFaqs] = React.useState<typeof faqs>([]);

  // Shuffle a fresh 20 questions every time the popup opens
  const openAllQuestions = React.useCallback(() => {
    const shuffled = [...faqs].sort(() => Math.random() - 0.5).slice(0, 20);
    setShuffledFaqs(shuffled);
    setPopupOpenFaqIndex(null);
    setIsAllQuestionsOpen(true);
  }, []);

  const filteredFaqs = React.useMemo(() => {
    if (!searchQuery.trim()) return faqs.slice(0, 5);
    const lowerQuery = searchQuery.toLowerCase();
    return faqs
      .filter(
        (faq) =>
          faq.q.toLowerCase().includes(lowerQuery) ||
          faq.a.toLowerCase().includes(lowerQuery),
      )
      .slice(0, 5);
  }, [searchQuery]);

  React.useEffect(() => {
    const checkMobile = () => setIsMobile(window.innerWidth < 640);
    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  }, []);

  return (
    <>
      <section className="py-24 bg-white dark:bg-[#0B0F19] relative overflow-hidden">
        <div className="absolute -left-40 top-40 w-96 h-96 bg-blue-300/30 rounded-full blur-[100px] dark:bg-blue-800/15"></div>
        <div className="absolute -right-40 bottom-40 w-96 h-96 bg-cyan-300/30 rounded-full blur-[100px] dark:bg-cyan-800/15"></div>
        <div className="absolute left-1/2 -translate-x-1/2 top-0 w-[600px] h-[300px] bg-gradient-to-b from-blue-200/20 via-transparent to-transparent rounded-full blur-[80px] dark:from-blue-900/10"></div>

        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="text-center mb-10">
            <div className="inline-flex items-center justify-center mb-6 text-slate-900 dark:text-white">
              <svg
                viewBox="0 0 24 24"
                fill="currentColor"
                className="w-10 h-10"
              >
                <path d="M12 0l2.5 9.5L24 12l-9.5 2.5L12 24l-2.5-9.5L0 12l9.5-2.5L12 0z" />
              </svg>
            </div>
            <h2 className="text-[36px] leading-tight font-bold text-slate-900 dark:text-white mb-6">
              Frequently Asked Questions
            </h2>
            <p className="text-slate-500 dark:text-slate-400 max-w-2xl mx-auto text-[16px] leading-relaxed">
              Have questions? Find answers to common questions below, or contact
              our friendly support team for personalized help. Getting reply
              quickly.
            </p>
          </div>

          <div className="relative group w-full mb-12">
            <div className="absolute inset-0 bg-gradient-to-r from-blue-100 to-cyan-100 dark:from-blue-900/20 dark:to-cyan-900/20 rounded-2xl blur-xl group-focus-within:opacity-100 opacity-0 transition-opacity duration-500"></div>
            <div className="relative flex items-center bg-white dark:bg-slate-900/80 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-sm hover:shadow-md transition-all focus-within:ring-2 focus-within:ring-blue-500/20 focus-within:border-blue-500/50 p-1.5 pl-5">
              <Search className="w-5 h-5 text-slate-400 group-focus-within:text-blue-500 transition-colors shrink-0" />
              <input
                type="text"
                value={searchQuery}
                onChange={(event) => setSearchQuery(event.target.value)}
                placeholder="Search your question..."
                className="w-full bg-transparent border-none focus:ring-0 text-slate-900 dark:text-white placeholder:text-slate-400 px-4 py-2 sm:py-2.5 outline-none text-[15px]"
              />
              {searchQuery && (
                <button
                  type="button"
                  onClick={() => setSearchQuery("")}
                  className="mr-2 p-1 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 transition-colors"
                >
                  <X className="w-4 h-4" />
                </button>
              )}
              <button className="bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-700 hover:to-cyan-700 text-white font-semibold py-2.5 px-5 sm:px-8 rounded-xl transition-all shrink-0 text-sm shadow-[0_2px_10px_rgba(37,99,235,0.2)] hover:shadow-[0_4px_15px_rgba(37,99,235,0.3)]">
                Search
              </button>
            </div>
          </div>

          <div className="space-y-1">
            {filteredFaqs.length > 0 ? (
              filteredFaqs.map((faq, index) => {
                const isOpen = openFaqIndex === index;
                return (
                  <div
                    key={index}
                    className="border-b border-slate-200 dark:border-slate-800/80 last:border-0"
                  >
                    <button
                      onClick={() => setOpenFaqIndex(isOpen ? null : index)}
                      className="w-full flex items-center justify-between py-5 text-left focus:outline-none group"
                    >
                      <span className="font-semibold text-slate-800 dark:text-slate-200 group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors pr-8">
                        {faq.q}
                      </span>
                      <span className="text-slate-400 shrink-0">
                        {isOpen ? (
                          <Minus className="w-5 h-5" />
                        ) : (
                          <Plus className="w-5 h-5" />
                        )}
                      </span>
                    </button>
                    <AnimatePresence>
                      {isOpen && (
                        <motion.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: "auto", opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          transition={{ duration: 0.2 }}
                          className="overflow-hidden"
                        >
                          <p className="pb-5 text-slate-600 dark:text-slate-400 text-[15px] leading-relaxed">
                            {faq.a}
                          </p>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                );
              })
            ) : (
              <div className="text-center py-10">
                <p className="text-slate-500 dark:text-slate-400">
                  No matching questions found.
                </p>
              </div>
            )}
          </div>

          <div className="mt-8 text-center">
            <button
              onClick={openAllQuestions}
              className="text-sm font-semibold text-slate-600 dark:text-slate-400 hover:text-blue-600 dark:hover:text-blue-400 underline underline-offset-4 transition-colors"
            >
              See all questions
            </button>
          </div>
        </div>
      </section>

      <AnimatePresence>
        {isAllQuestionsOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-end justify-center bg-black/30 p-0 backdrop-blur-sm sm:items-center sm:p-6"
            onClick={() => setIsAllQuestionsOpen(false)}
            role="dialog"
            aria-modal="true"
          >
            <motion.div
              variants={isMobile ? mobileVariants : desktopVariants}
              initial="initial"
              animate="animate"
              exit="exit"
              transition={{ ease: [0.16, 1, 0.3, 1], duration: 0.3 }}
              className="relative w-full h-[90vh] sm:h-[80vh] flex flex-col overflow-hidden rounded-t-2xl shadow-xl sm:rounded-[28px] sm:max-w-2xl border border-slate-200/70 bg-white dark:border-slate-700/50 dark:bg-slate-900"
              onClick={(event) => event.stopPropagation()}
            >
              <div className="flex items-start justify-between gap-3 p-4 sm:p-6 border-b border-slate-100 dark:border-slate-800 shrink-0 relative z-10 bg-white/80 dark:bg-slate-900/80 backdrop-blur-md">
                <div className="min-w-0 flex-1">
                  <h3 className="text-xl font-bold text-slate-900 dark:text-white">
                    All Questions
                  </h3>
                  <p className="inline-flex items-center gap-1.5 mt-1.5 px-2.5 py-1 rounded-md bg-blue-50 dark:bg-blue-900/30 text-xs font-medium text-blue-600 dark:text-blue-400 border border-blue-100 dark:border-blue-800/50">
                    <Search className="w-3 h-3 shrink-0" />
                    Search to find your answer you need
                  </p>
                </div>
                <button
                  type="button"
                  onClick={() => setIsAllQuestionsOpen(false)}
                  className="mt-0.5 shrink-0 flex h-9 w-9 items-center justify-center rounded-full border border-slate-200/80 bg-slate-50 text-slate-400 transition hover:border-slate-300 hover:text-slate-700 dark:border-slate-700 dark:bg-slate-800 dark:hover:border-slate-600 dark:hover:text-slate-200"
                >
                  <X className="h-4 w-4" />
                </button>
              </div>

              <div className="flex-1 overflow-y-auto p-4 sm:p-6 space-y-1">
                {shuffledFaqs.map((faq, index) => {
                  const isOpen = popupOpenFaqIndex === index;
                  return (
                    <div
                      key={index}
                      className="border-b border-slate-100 dark:border-slate-800/80 last:border-0"
                    >
                      <button
                        onClick={() =>
                          setPopupOpenFaqIndex(isOpen ? null : index)
                        }
                        className="w-full flex items-center justify-between py-4 text-left focus:outline-none group"
                      >
                        <span className="font-medium text-[15px] text-slate-800 dark:text-slate-200 group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors pr-8">
                          {faq.q}
                        </span>
                        <span className="text-slate-400 shrink-0">
                          {isOpen ? (
                            <Minus className="w-4 h-4" />
                          ) : (
                            <Plus className="w-4 h-4" />
                          )}
                        </span>
                      </button>
                      <AnimatePresence>
                        {isOpen && (
                          <motion.div
                            initial={{ height: 0, opacity: 0 }}
                            animate={{ height: "auto", opacity: 1 }}
                            exit={{ height: 0, opacity: 0 }}
                            transition={{ duration: 0.2 }}
                            className="overflow-hidden"
                          >
                            <p className="pb-4 text-slate-600 dark:text-slate-400 text-sm leading-relaxed">
                              {faq.a}
                            </p>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
                  );
                })}
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
